### ISSUE TITLE
[Request] Checksum for other installers besides Windows

### ISSUE THREAD

**Issue by tuanpham96** [jupyterlab/jupyterlab-desktop#502]
Currently the only available checksum available on [Releases](https://github.com/jupyterlab/jupyterlab-desktop/releases) (in `latest.yml` file) is `sha512` for Windows (`.exe` installer). For example, with version `3.4.6-1`:

``` yaml
version: 3.4.6-1
files:
  - url: JupyterLab-Setup.exe
    sha512: VkgOHAkwasGIZeYh/4i0u4sTon7tgyIAOq7J5vjCsYr5ga5vwgChpicUBcFqyoKgzGH2I9VYnF9sg2FfLH4NkA==
    size: 557687912
path: JupyterLab-Setup.exe
sha512: VkgOHAkwasGIZeYh/4i0u4sTon7tgyIAOq7J5vjCsYr5ga5vwgChpicUBcFqyoKgzGH2I9VYnF9sg2FfLH4NkA==
releaseDate: '2022-09-09T05:48:04.707Z'
```

It would be nice to have (at least) `sha512` for Linux and MacOS installers as well, especially because currently we'd have to download the installers every time an update is available. 

Thanks!
